### ISSUE TITLE
Create roles for SONiC switch monitoring

### ISSUE THREAD

**Issue by majst01** [metal-stack/metal-roles#110]
One possible solution would be: https://github.com/STORDIS/monsoon/

**Comment by GrigoriyMikhalkin** [comment]
I found few other solutions that can be used for monitoring different parts:
- [sFlow](https://blog.sflow.com/2020/02/sonic.html) -- it's already can be activated as a feature on SONiC and there's [sFlow exporter](https://github.com/sflow-rt/prometheus) for Prometheus.
- [SONiC Telemetry service](https://github.com/sonic-net/sonic-gnmi/blob/master/doc/grpc_telemetry.md) -- with some tinkering(there exist gNMI plugins for Prometheus) also can be used for monitoring.

There's also few monitoring services [running by default in SONiC](https://github.com/sonic-net/SONiC/blob/master/doc/system_health_monitoring/system-health-HLD.md) -- `monit` and `pmon`. But looks like there's no exclusive data there, that can't be gotten from aforementioned services.

Also, before choosing what services to use, would be nice to understand what we definitely want to monitor.
