### ISSUE TITLE
Mgmt VRF support in sonic flavor

### ISSUE THREAD

**Issue by mwindowergh** [metal-stack/metal-roles#183]
When using the metal-roles/sonic role to install a SONiC switch we get a strange behavior regarding the mgmt VRF.

`show mgmt-vrf` shows that it is enabled but no linux devices are listed and also eth0 is not part of the mgmt VRF.

As workaround we remove tha mgmt VRF and readd it with the CLI.

@robertvolkmann @mreiger did you experience such a behavior as well?

**Comment by mwindower** [comment]
Also we encountered two issues at exit switches:
- interface Ethernet0 was not bound to the VRF mentioned in the role parameters: `config vrf add VrfIsp; config interface vrf bind Ethernet0 VrfIsp`
- the VRF needs to be mapped to the correct L2VNI
```
"VRF": {
  "VrfIsp": {
    "vni": "10400x"
  }
}

**Comment by Gerrit91** [comment]
How important is this? Does somebody need to work on it or can we close this because implementation will never happen?

**Comment by mwindower** [comment]
The vrf is not used in any SONiC partition.
Mapping of VRFs to VNI is already supported by the ansible-role for sonic.
