### ISSUE TITLE
Create roles for dns, ntp and registry

### ISSUE THREAD

**Issue by majst01** [metal-stack/metal-roles#235]
Move existing roles from metal-deployment into dedicated roles here

Related to: https://github.com/fi-ts/proxy-services/issues/4

Requirements for the registry:

- Deployed on every seed
- external access restricted by the usage of loadbalancer source ranges
- Make the image overrides configurable
- Use persistent volumes as backing store
- Multiple instances with same ip, use ECMP for loadbalancing

DNS:
- ...

NTP:
- ...

**Comment by Gerrit91** [comment]
This does not need to go into v0.17.0 release for isolated cluster support but for the community it would be great to push this automation into this repository.

**Comment by Gerrit91** [comment]
Done.
