### ISSUE TITLE
Docker Logs might consume all disk space on Switches

### ISSUE THREAD

**Issue by vknabel** [metal-stack/metal-roles#285]
After some time running the `grafana/promtail` container logs consume all free space on the disk ultimately resulting in failing switch syncs.
It would make sense to limit the amount of logs to prevent this.

**Comment by majst01** [comment]
Can you identify what exactly must be done to restrict the log volume ?

**Comment by vknabel** [comment]
Not sure how, but we need to set the options in https://docs.docker.com/config/containers/logging/json-file/

**Comment by majst01** [comment]
> Not sure how, but we need to set the options in https://docs.docker.com/config/containers/logging/json-file/

This applies to all other containers on the switch then, maybe there is some SONiC documentation on this topic

**Comment by majst01** [comment]
Be aware that this affects all switches and management servers with the consequence that all daemons which are started with docker will be restarted

**Comment by vknabel** [comment]
With the solution all daemons started by the `systemd-docker-service` role will be restarted. If understand it correctly this does not apply sonic's daemons only 'ours'.
